<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dolebas_payment_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dolebas_custom module.
    case 'help.page.dolebas_payment':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom code') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dolebas_payment_theme() {
  return [
    'dolebas_payment' => [
      'template' => 'dolebas_payment',
      'render element' => 'children',
    ],
  ];
}
