<?php

//use Drupal\Core\Routing\RouteMatchInterface;
//
///**
// * Implements hook_help().
// */
//function dolebas_payments_help($route_name, RouteMatchInterface $route_match) {
//  switch ($route_name) {
//    // Main module help for the dolebas_payment module.
//
//    case 'help.page.dolebas_payment':
//      $output = '';
//      $output .= '<h3>' . t('About') . '</h3>';
//      $output .= '<p>' . t('Custom code') . '</p>';
//      return $output;
//
//    default:
//  }
//}

/**
 * Implements hook_theme().
 */

function dolebas_payments_theme() {

  $theme['stripe_elements'] = array(
    'variables' => array(
      'var1' => NULL,
    ),
    'template' => 'stripe_elements',
  );

  $theme['stripe_checkout'] = array(
    'variables' => array(
      'var1' => NULL,
    ),
    'template' => 'stripe_checkout',
  );

  return $theme;

}
